apiVersion: v1
kind: ConfigMap
metadata:
  name: vdi-config
data:
  MONGO_DATABASE: vdi
  HTTP_ADDR: ':8080'
  VDI_SERVICE_ID: devoops-vdi
  OS_REGION_NAME: RegionOne
  OS_NETWORK_ID: replace-network-uuid
  OS_SECURITY_GROUPS: rdp
  EXTERNAL_TIMEOUT: 10s
  POLL_INTERVAL: 5s
  READY_TIMEOUT: 15m
  GUAC_URL_TTL: 2m
  GUAC_URL: https://vdi.example.com/guacamole/
